name: build-apt-repo
on:
  push:
    branches: [main]
  workflow_dispatch:

# 커밋/푸시할 권한
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure docs folders
        run: |
          mkdir -p docs/debs
          touch docs/.nojekyll

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev apt-utils bzip2 apt-transport-https gnupg

      - name: Build Packages/Release
        shell: bash
        run: |
          set -eux
          cd docs

          # .deb이 하나라도 있을 때만 생성
          if compgen -G "debs/*.deb" > /dev/null; then
            dpkg-scanpackages ./debs > Packages
            bzip2 -kf Packages

            cat > aptftp.conf << 'EOF'
            Dir { ArchiveDir "."; }
            Default { Packages::Compress ". gzip bzip2"; }
            BinDirectory "debs" { Packages "Packages"; }
            APT::FTPArchive::Release::Origin "MyRepo";
            APT::FTPArchive::Release::Label "MyRepo";
            APT::FTPArchive::Release::Suite "stable";
            APT::FTPArchive::Release::Codename "ios";
            APT::FTPArchive::Release::Architectures "iphoneos-arm iphoneos-arm64 all";
            APT::FTPArchive::Release::Components "main";
            EOF
