name: build-apt-repo
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure folders
        run: |
          mkdir -p docs/debs
          touch docs/.nojekyll

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev apt-utils bzip2 apt-transport-https gnupg

      - name: Build Packages/Release
        shell: bash
        run: |
          set -eux
          cd docs
          # Packages 생성 (debs가 비어도 빈 파일로 생성)
          if compgen -G "debs/*.deb" > /dev/null; then
            dpkg-scanpackages debs > Packages
          else
            : > Packages
          fi
          bzip2 -kf Packages

          # Release(필수 헤더 포함)
          cat > aptftp.conf << 'EOF'
          Dir { ArchiveDir "."; }
          Default { Packages::Compress ". gzip bzip2"; }
          BinDirectory "debs" { Packages "Packages"; }
          APT::FTPArchive::Release::Origin "MyRepo";
          APT::FTPArchive::Release::Label "MyRepo";
          APT::FTPArchive::Release::Suite "stable";
          APT::FTPArchive::Release::Codename "ios";
          APT::FTPArchive::Release::Architectures "iphoneos-arm iphoneos-arm64 all";
          APT::FTPArchive::Release::Components "main";
          EOF
          apt-ftparchive -c=aptftp.conf release . > Release

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/Packages docs/Packages.bz2 docs/Release docs/.nojekyll || true
          git commit -m "Build repo metadata" || echo "No changes"
          git pull --rebase
          git push
